# INCREASING THE TRAINING SET AND DESCREASING THE TESTING SET TO SEE IF THE WE CAN GET 100% ACCURACY WITH OUR MODEL
# TAKING 99.9985% OF THE DATASET TO TRAIN MY MODEL
# TAKING 0.0015% OF THE DATASET TO TEST (APPROX 2 PATIENTS WILL BE TEST OUT OF 700)
# RESULT : 100% ACCURACY IS ACHIEVED

